### ISSUE TITLE
Add WasherDryer implementation

### ISSUE THREAD

**Issue by yusijs** [DavidMStraub/homeassistant-homeconnect#101]
https://developer.home-connect.com/docs/washer-dryer/supported_programs_and_options

**Comment by VVlasy** [comment]
Will this ever be merged to HA Core?

**Comment by DavidMStraub** [comment]
You asked that elsewhere as well. Once is enough. If you are in a hurry, submit a PR yourself.

**Comment by maceace** [comment]
I do not understand the principle of this throwing the problem from one to the other. 
It is not necessary to understand this. 
The only thing I would like to find out is, will my washer and dryer ever connect to the HA? 
Or no one is working on it, and connecting to Home Assistant is not on the horizon.

**Comment by DavidMStraub** [comment]
I was trying to help anybody who has time to work on this find a solution quicker.

What you do have to understand is that if you want to motivate somebody to work on a feature you need in their free time, you won't have success if you write in a presumptuous tone and treat developers like your employees.
