### ISSUE TITLE
Connection to the API Seems to Drop out

### ISSUE THREAD

**Issue by jamiewalters** [DavidMStraub/homeassistant-homeconnect#108]
I am not sure if this belongs here but perhaps I can get some tips on what might be the issue:
I notice that for some appliances, the connection? seems to drop randomly for hours. I have automation attached to say the dryer progress, and today for eg., It stopped updating at 6am and resumed around 5pm. So all day I was using the dryer, nothing was being reported. I noticed that sometimes its the same for the washing machine, it stops reporting the door sensor so  it is closed for several hours despite being opened.  What is odd is that during this time, I can see it being updated in the app.

**Comment by DavidMStraub** [comment]
If it is returning to normal at some point, I suspect it's a problem with the API servers..

**Comment by jamiewalters** [comment]
Could likely be so, just makes it less reliable when used in automations.

**Comment by DavidMStraub** [comment]
There is also this issue https://github.com/DavidMStraub/homeconnect/issues/3, but in that case it doesn't return to normal.
