### ISSUE TITLE
Aborted

### ISSUE THREAD

**Issue by jamiewalters** [DavidMStraub/homeassistant-homeconnect#109]
In trouble shooting an issue, I removed the integration and tried to re-add it. However it just now says "Aborted" and fails while trying to re-add it. Any known issue that causes this behaviour?

**Comment by DavidMStraub** [comment]
I'm not aware of any.

**Comment by J3n50m4t** [comment]
I've got the same problem. 
I've tried to get some logging but even with debug I don't get any related logs. 

Home Assistant 0.115.6

config can be found here: 
https://github.com/J3n50m4t/HomeAssistantConfiguration/blob/3c1a231ac8a0889492b001afe15525d3a44bf252/configuration.yaml#L28

Thats literally everything: 
```
home-assistant   | 2020-10-05 20:35:13 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 172.17.0.5 for /api/config/config_entries/flow using bearer token
home-assistant   | 2020-10-05 20:35:13 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/config/config_entries/flow to 172.17.0.5 (auth: True)
```

**Comment by DavidMStraub** [comment]
Have you added the integration in the UI under "integrations"?

**Comment by J3n50m4t** [comment]
Yes i did.. 
Update: 
I've downgraded to 0.114.4 and Adding the Integration shows 
{
  "error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized",
  "state": "removed this token"
}

**Comment by J3n50m4t** [comment]
Adding the Integration at Version 0.114.4 works fine.  
After Updating it again I was also able to add it. 
I did exactly the same few hours ago without any luck.

**Comment by DavidMStraub** [comment]
You're not even using the beta integration, so this is the wrong repository to post.

**Comment by jamiewalters** [comment]
Now I get this:

Aborted
The Home Connect component is not configured. Please follow the documentation.

This is my config:

home_connect_beta:
  client_id: xxxxxx
  client_secret: xxxxx

Am I missing a config param?

**Comment by DavidMStraub** [comment]
No

**Comment by jamiewalters** [comment]
ok, thanks.

**Comment by jamiewalters** [comment]
For anyone else that might have a similar issue, this solved this problem:

https://www.home-assistant.io/more-info/no-url-available
