### ISSUE TITLE
UNIT PERCENTAGE

### ISSUE THREAD

**Issue by t0bse** [DavidMStraub/homeassistant-homeconnect#110]
The UNIT_PERCENTAGE constant was changed to PERCENTAGE since 0.115 this causes an error:

Component error: home_connect_beta - cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

could you please fix this? :)

**Comment by DavidMStraub** [comment]
Duplicate of #106.
