### ISSUE TITLE
cannot import name 'UNIT_PERCENTAGE'

### ISSUE THREAD

**Issue by gomble** [DavidMStraub/homeassistant-homeconnect#112]
Hello i get the following error since homeassistant update 0.115.
See following issue: https://github.com/home-assistant/core/issues/40207

Logger: homeassistant.setup
Source: setup.py:138
First occurred: 21:28:05 (1 occurrences)
Last logged: 21:28:05

Setup failed for homeconnect: Unable to import component: cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by DavidMStraub** [comment]
You are the 4th person to report this. There is a search function. This is already fixed in master. #106

**Comment by gomble** [comment]
Yes but i saw that the component now is available in the offical homeassistant core.
I deleted the custom_component but now i get this error:
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:365
Integration: Hass.io (documentation, issues)
First occurred: 22:36:17 (1 occurrences)
Last logged: 22:36:17

Component error: homeconnect - Integration 'homeconnect' not found.
