### ISSUE TITLE
Detect remote start is enabled on the machine

### ISSUE THREAD

**Issue by golles** [DavidMStraub/homeassistant-homeconnect#113]
Hi,

The one thing I would really as this component gets is a sensor that contains the state of a machine.

The main use case here is that I want to set my dishwasher into remote control mode and then let Home Assistant switch it on at a given time from an automation.
In this situation, I wouldn't need to do this every evening in the home connect app.

**Comment by DavidMStraub** [comment]
Duplicate of #99
