### ISSUE TITLE
token not renewing

### ISSUE THREAD

**Issue by Svrbinek** [DavidMStraub/homeassistant-homeconnect#116]
When the token expires, the Home Assistant does not request a new one. I have no idea why, but it can be seen in the log. Then it will always help to restart HA for only about 24 hours (?) Or in the integration to select to restore Home Connect again.
Could you please find out why it is not being restored? HA I have the current version Home Assistant 0.117.6

**Comment by Svrbinek** [comment]
Here is an error from the log:
Logger: homeconnect
Source: /usr/local/lib/python3.8/site-packages/homeconnect/api.py:72
First time occurred: November 12, 2020 7:07:24 PM (1 occurrences)
Last login: November 12, 2020 7:07:24 PM

The token has expired.

**Comment by tinus20vt** [comment]
> Here is an error from the log:
> Logger: homeconnect
> Source: /usr/local/lib/python3.8/site-packages/homeconnect/api.py:72
> First time occurred: November 12, 2020 7:07:24 PM (1 occurrences)
> Last login: November 12, 2020 7:07:24 PM
> 
> The token has expired.
> 
> https://pastebin.com/Dx0v66qV

Did you find a solution fir this?
I've the same problem

**Comment by Svrbinek** [comment]
> > Zde je chyba z protokolu: 
> > Logger: homeconnect 
> > Zdroj: /usr/local/lib/python3.8/site-packages/homeconnect/api.py:72 
> > Poprvé došlo: 12. listopadu 2020 19:07:24 ( 1 výskyt) 
> > Poslední přihlášení: 12. listopadu 2020 19:07:24
> > Platnost tokenu vypršela.
> > https://pastebin.com/Dx0v66qV
> 
> Našli jste řešení?
> Mám stejný problém

I didn't find a solution. Still a problem and I expected one of the developers to respond but none.

**Comment by seaniedan** [comment]
I've had this problem too. I've detailed my logs on #125 ..maybe you could have a look there too. I've not had a response from the developer except that he blames my internet connection (though that's working fine).

**Comment by DavidMStraub** [comment]
Note that token refresh is handled by Home Assistant core, so this repository is the wrong place to report issues with it, unless you have a reason to expect that something specific to this beta version is causing the issue.
