### ISSUE TITLE
Turn on/off the functional light of the hood

### ISSUE THREAD

**Issue by allmoney** [DavidMStraub/homeassistant-homeconnect#118]
Now no way to turn on/off the functional light of the hood from HA. I asked support about this feature in API and they answered:

You can turn on/off the functional light of the hood by modifying the Cooking.Common.Setting.Lighting setting. More information can be found here:
https://developer.home-connect.com/docs/api/settings/functionallight

Please, can you add this feature to HA integration?

**Comment by anthonyangel** [comment]
This was added in https://github.com/DavidMStraub/homeassistant-homeconnect/pull/105 I thought

**Comment by Sjack-Sch** [comment]
This feature is part of HA Core release 2021.1.1

**Comment by allmoney** [comment]
Why no information about it here? https://github.com/home-assistant/core/releases/tag/2021.1.1

**Comment by allmoney** [comment]
![image](https://user-images.githubusercontent.com/939594/104702727-76003c00-5727-11eb-954b-66e070993e79.png)
Now I can control light! Cool!
But I have 2 switches in UI - Light & AmbientLight. Light works! AmbientLight does not do anything.

**Comment by Sjack-Sch** [comment]
> Why no information about it here? https://github.com/home-assistant/core/releases/tag/2021.1.1

It was mentioned here: https://www.home-assistant.io/blog/2021/01/06/release-20211/
:-)

**Comment by Sjack-Sch** [comment]
> ![image](https://user-images.githubusercontent.com/939594/104702727-76003c00-5727-11eb-954b-66e070993e79.png)
> Now I can control light! Cool!
> But I have 2 switches in UI - Light & AmbientLight. Light works! AmbientLight does not do anything.

AmbientLight only works with supported devices. When your hood does not support ambient light the switch should be removed from the HA UI.

**Comment by Sjack-Sch** [comment]
@DavidMStraub, I believe this issue can be closed.
