### ISSUE TITLE
Expired token not refreshed

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/homeassistant-homeconnect#12]
HA log:

```
homeconnect.api.HomeConnectError: {'description': 'The access token expired', 'key': 'invalid_token'}
```

This should not have happened; rather, the refresh token should have been used to fetch a new one.

**Comment by zufivan** [comment]
Hi David,
I installed the component 10 day ago, for me every day the token refresh automatically.

**Comment by DavidMStraub** [comment]
Thans @zufivan, that's good to know. Indeed after restarting HA the component automatically refreshed the token again. Surprising that this happened, but I'll close this for now.
