### ISSUE TITLE
Oven-control scope not granted

### ISSUE THREAD

**Issue by PimButton** [DavidMStraub/homeassistant-homeconnect#13]
Hi David,

Thanks so much for your work on the component, it's great!
I currently have a Siemens Home Connect enabled oven and am trying to hook it up to Home Assistant. I have followed all the steps as outlined in the readme and it seems to work fine. When I open or close the oven door the 'Door' entity gets updated correctly. The 'on' switch does not work, as per #10 . 

However, all of the other oven controls (Pre heating, Hot air, etc) do not work. The log shows `homeconnect.api.HomeConnectError: {'description': 'Insufficient scope for this resource', 'key': 'insufficient_scope'}`
If I check the Granted Scopes table in the Home Connect developer Program for the application that I have created the `oven-control` scope in the Control column is greyed-out. Please see the attached screenshot. 

![schermafbeelding 2019-02-17 om 14 57 28](https://user-images.githubusercontent.com/7047181/52914087-64f0eb00-32c4-11e9-8c70-b3b2fd33e19f.png)

Do you by any chance know how to enable this? I cannot seem to find a setting somewhere to enable it... Thanks in advance, your work is much appreciated!

**Comment by DavidMStraub** [comment]
Hi,

interesting; for me it looks the same (but I don't have a physical oven just yet ... will get one in a few weeks). What I suspect is that they have not enabled this feature in the API yet (although from the docs it should work). Could you send an e-mail to the API developers on that issue? They are usually quite responsive and helpful.

**Comment by EspenT** [comment]
Any news here?

**Comment by thoukydides** [comment]
According to https://developer.home-connect.com/docs/authorization/scope, the `Oven-Control`,
`FridgeFreezer-Control`, `Hob-Control`, and `FridgeFreezer-Images` scopes require an "**Additional Partner Agreement**".

The [Home Connect Developer Agreement](https://developer.home-connect.com/developer_agreement) also says:
> Certain additional permissions to those specified at: https://developer.home-connect.com/docs/authorization/scope may be granted to Clients of selected Users upon an individual check by HC and upon agreement of a separate partner agreement between the Parties, which is based on this Agreement.

With open source software where each user creates their own developer account it would be necessary for each user to do this... and I suspect that won't pass the "individual check by HC".

**Comment by DavidMStraub** [comment]
Interesting, I wasn't aware of this, thanks @thoukydides.

Now that I have an oven myself, I can confirm that I cannot control it either, but switching on and off should work in principle apart from #10 that I still have to fix (next on my list...).

**Comment by minscof** [comment]
I have the same problem : oven-control scope not granted.
Does anyone know the procedure to get the agreement with the partner ?

**Comment by DavidMStraub** [comment]
I don't think it's realistic.

But once this component becomes an official part of Home Assistant, they might be able to get an agreement for Home Assistant Cloud.

**Comment by thoukydides** [comment]
> I have the same problem : oven-control scope not granted.
> Does anyone know the procedure to get the agreement with the partner ?

I recently asked [Home Connect developer support](https://developer.home-connect.com/support/contact) about `Oven-Control` and `Hob-Control` scopes. They provided the following response:
> We are discussing your case, and similar internally now, while unfortunately like you noticed agreement with Home Connect is for business users, due to legal limitations, and potential risk of not correct usage of Hob (actually event with this scope it is not possible at this moment to control Hob via API, as there is no program which you could use) or Oven.  
>
> Never less I will inform you about results of this discussion soon

**Comment by DavidMStraub** [comment]
Thanks, that's very interesting! Keep us posted :+1:

**Comment by Blogem** [comment]
Ever heard anything back from them @thoukydides ?

**Comment by thoukydides** [comment]
Sorry, @Blogem, I haven't received any further feedback from the Home Connect team. It's particularly frustrating now that IFTTT is going to stop being useful without a paid subscription.

**Comment by DavidMStraub** [comment]
FYI, Paulus wrote to me in May that he is looking into obtaining this permission on behalf of Home Assistant (or Nabu Casa), so this feature could be used together with the HA account linking service. But I don't know what the status of this is.
