### ISSUE TITLE
part of the entities siemens dishwasher is unavailable

### ISSUE THREAD

**Issue by ananyevgv** [DavidMStraub/homeassistant-homeconnect#132]
Good afternoon after updating to core-2021.8.0 it became unavailable part of the entities of the siemens dishwasher
![image](https://user-images.githubusercontent.com/81970899/128480861-5ee92588-58a5-4d66-ac49-3a243ea470aa.png)
![image](https://user-images.githubusercontent.com/81970899/128480936-832cee16-f3c2-4609-8f8b-7113d447254b.png)

**Comment by ananyevgv** [comment]
![image](https://user-images.githubusercontent.com/81970899/128481747-372bda1a-4ac0-4c13-a5ad-b6e447527e00.png)

**Comment by DavidMStraub** [comment]
Are you using the integration in Home Assistant or the beta integration from this repository?

**Comment by DavidMStraub** [comment]
Ah sorry, I can see from your screenshort that it's the official integration. Then please report it in the official repo if you think it's a bug.
