### ISSUE TITLE
Implement HomeConnect service to set specific program / incl. details

### ISSUE THREAD

**Issue by MvQuast** [DavidMStraub/homeassistant-homeconnect#137]
At the moment, there's only the option to start predefined programs from an oven (for example), but HC API also allows to set temperature/duration as well. Ideally, HC integration should expose this as a service to get input params from an Alexa conversatio. through NodeRed

**Comment by DavidMStraub** [comment]
Duplicate of #23, but anyway as stated in the Readme please refer to HA core.
