### ISSUE TITLE
Home Connect integration has a problem connecting devices #72486

### ISSUE THREAD

**Issue by maceace** [DavidMStraub/homeassistant-homeconnect#139]
I have two Home Connect devices
The dishwasher connects to the Home Connect integration without any problems.
Second, the washer-dryer is properly connected to both the Home Connect cloud and the mobile application.
The problem is, this device cannot be added to the Home Integration Assistant.
I spoke with the support of the appliance manufacturer for Home Connect, I was told that they were interested in integrating their appliances into the Home Assistant. Their system is open to Home Assistant and other projects.
Therefore, I think there is some shortcoming in integration for HA.

can please check it?

**Comment by DavidMStraub** [comment]
Please raise issues at HA Core, see Readme.

**Comment by maceace** [comment]
> 

That's what I did. A few days back. Still no response.

**Comment by maceace** [comment]
> Please raise issues at HA Core, see Readme.

https://github.com/home-assistant/core/issues/72486
