### ISSUE TITLE
Directory structure needs changed, warnings after 0.88.0 upgrade

### ISSUE THREAD

**Issue by ltjessem** [DavidMStraub/homeassistant-homeconnect#14]
`WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change sensor/homeconnect.py to homeconnect/sensor.py. This will stop working soon.`

I've manually moved `binary_sensor/homeconnect.py`, `sensor/homeconnect.py` and `switch/homeconnect.py` in my installation to `homeconnect/binary_sensor.py`, `homeconnect/sensor.py` and `homeconnect/switch.py`, this seems to be working fine at first glance.

**Comment by DavidMStraub** [comment]
Indeed! This new folder structure also makes managing the custom component much easier. Should be fixed now.
