### ISSUE TITLE
Save more properties of the devices

### ISSUE THREAD

**Issue by robvanuden** [DavidMStraub/homeassistant-homeconnect#16]
It would be nice if more properties are saved. Every property via the SSE connection could be saved in the attributes of a sensor. These can be used in template sensors for example.
For example the currently selected program or the "remote control allowed state" of a dishwasher aren't visible yet in HA. 
I think we can start saving it as attributes and maybe later on adding more "real" sensors.

I'm new to python, but I think it's something I could work on.

Let me know what you think.

**Comment by DavidMStraub** [comment]
I think that's a good idea. But if we add a sensor it also needs to have a "value" (besides the attributes) and a name. What would you suggest for that? Maybe just 'on' or 'off' (i.e. a binary sensor)?

**Comment by robvanuden** [comment]
It depends on the property.
The "remote control allowed state" would be a binary sensor, the currently selected program a sensor (or maybe even an input select).
Let's save the properties first as attributes and check what sensors/switches would be useful.

**Comment by DavidMStraub** [comment]
Right, what I meant was where to save the attributes in the first step (where there are no dedicated sensors/switches yet).

**Comment by robvanuden** [comment]
I think it's the most clear to create one sensor per device.

**Comment by DavidMStraub** [comment]
If you want to give this a shot, I'd be happy about a PR :+1:

**Comment by robvanuden** [comment]
We could at it also to the power switch (there is already one per device right?)
I will work on it, but have to get used to Python etc, so not sure how long it will take.

**Comment by DavidMStraub** [comment]
Yes, adding it to the power switch is a good idea!

**Comment by DavidMStraub** [comment]
This is implemented now. I decided to shorten the long attribute names like `BSH.Common.EnumType.DoorState.Closed` to simply `closed`. Example:

<img width="263" alt="Screenshot_20191119_160303" src="https://user-images.githubusercontent.com/10965193/69158060-20f67500-0ae6-11ea-94e4-4a23f2e7f753.png">
