### ISSUE TITLE
"error": "unauthorized_client",

### ISSUE THREAD

**Issue by onkelfarmor** [DavidMStraub/homeassistant-homeconnect#2]
Can you explain a bit further, what to do on developer.home-connect.com.
I have registered for an account, made an application, but get error. Should I do more?

{
  "error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized",
  "state": "bRl6aNDDAcf6sRuxYYUuJ5yilThuDv"
}

**Comment by DavidMStraub** [comment]
Hi,

you need to
- enter the correct Redirect URI in the App's settings
- make sure you have Status set to Enabled in the App's settings
- make sure you have the app's client ID & client secret in your configuration.yaml.

Do you have all that?

**Comment by onkelfarmor** [comment]
Sorry, hadn't activated ssl in my home-assistant setup :-(
Now it works!

I get the following sensor/switch:
               - sensor.dryer_program_progress
               - sensor.dryer_remaining_program_time
               - binary_sensor.dryer_door
               - switch.dryer
               - switch.dryer_program_cotton
               - switch.dryer_program_mix
               - switch.dryer_program_synthetic

but only sensor.dryer_remaining_program_time is updated. Moreover it shows time in seconds, could be nice with hours/minutes.

**Comment by DavidMStraub** [comment]
> but only sensor.dryer_remaining_program_time is updated

I had a bug (#1) that I fixed seconds ago that the program switch for a  program running at startup of HA does not have the correct state. Maybe that affected you as well. As to the program_progress sensor, that does not seem to exist for the dryer (a dryer is the only physical HC device I own, too), but I left it in since the API claims it exists in principle.

> Moreover it shows time in seconds, could be nice with hours/minutes.

Indeed, that's annoying for a dryer. But I haven't found out how to do that yet in HA. Of course one could turn the sensor value into a string, but that would make it impossible to use in automations. There should be some kind of pretty formatting of time values in HA...

**Comment by onkelfarmor** [comment]
thanks

**Comment by kaareseras** [comment]
How did you enable SSH?

**Comment by TorbjornZachrisson** [comment]
I´m having the same problem. I have ssl enabled and are connecting from outside on port 443 but the router are forwarding to port 8123 internal. Somehow the 8123 port gets sent for the authentication. Copied some of the url below. Figgelbo.duckdns.org%3A8123%2Fapi%2Fhomeconnect&state. This in not normally a problem...

**Comment by TorbjornZachrisson** [comment]
Changed in the code to add one more parameter on home assistant configuration. redirect_uri: https://xxxx.duckdns.org/api/homeconnect. Now it works.

**Comment by kaareseras** [comment]
@TorbjornZachrisson  I did as you descriped, changed the code and added the redirect uri. I the did the the authproces, and got all the way to the clicking the autorize button. Then I was rdirected to: https://xxxxxxx.xxx/api/homeconnect?code=eyJ4LIiwieC1lbnYiOiJQUkQiLCJ0b2tlbiI6Ijc4ZGQ2ODA2LTEyZDAtNDgzNy05ZGZiLTA0NDYwYWJjM2ZkZiJ9&state=Mewwr5Z2QlXwjg14zznPfO8x32dHUY&grant_type=authorization_code 
and got a 500 internal error.

My redirect in the config: redirect_uri: https://xxxxxx.xxx/api/homeconnect
and in the portal it is https://xxxxxx.xxx/api/homeconnect

What am I doing wrong?

**Comment by harko-aviva** [comment]
I am having the same issue with the 500 server error.. not sure what needs to be fixed.. Any tips? double checked the settings

**Comment by DavidMStraub** [comment]
Also the `base_url` on `http`?

**Comment by harko-aviva** [comment]
Yes, I am thinking I should have use device flow for the oauth flow now?

**Comment by DavidMStraub** [comment]
No, only authorization code grant flow works.

**Comment by harko-aviva** [comment]
![image](https://user-images.githubusercontent.com/48920622/61623294-a3754200-ac76-11e9-822c-7e2f1b18e4b4.png)

So this should be right for the settings than?

Thanks for your fast replies

**Comment by harko-aviva** [comment]
/api/homeconnect is giving me a 500 server error, not sure where to find the actual cause for that

**Comment by harkoprinssen** [comment]
Ah, when trying the HC api I get a similar error, must be some configuration in my account I did wrong than

**Comment by DavidMStraub** [comment]
> So this should be right for the settings than?


Your image is cut.

**Comment by harkoprinssen** [comment]
Didn't want to share my full url and tokens :)
Mainly wondering about the last 2 checkboxes

**Comment by harkoprinssen** [comment]
Think I figured it out, somehow it adds ":443" to my redirect uri. removing that sends to log in to the HC portal. now figure out how to allow myself access

**Comment by harkoprinssen** [comment]
Working now. the user account to give access to your testing should be the email-address of your normal home connect account. All working now, cheers!

**Comment by Christianb233** [comment]
Hello David, sorry to disturb with that but I have a "client or redirection URI not authorized" error :-(
I have followed all the instruction here https://www.home-assistant.io/integrations/home_connect/
I have put https://nameofmyduckdns.duckdns.org:8123/auth/external/callback (with :8123, with :443, wihtout :8123), but the error is still there when I try Configuration > Integrations > Home Connect
Can you help me to know what is missing in my process ?

**Comment by DavidMStraub** [comment]
Make sure you set the `internal_url` as well and watch this issue: https://github.com/home-assistant/core/issues/35844

**Comment by Christianb233** [comment]
Ok, after reading the different comment, I have changed external to internal url, and it enable to api.home-connect.com. Good :-) but by writing the smartphone home connect api login/password, the answer is "the corresponding user is not affected to this application into Home Connect Developer Portal." :-( I didn't catch that there was previously a "link" to do into Home Connect Developer Portal= I have only made the instructions "register new application > Home Assistant > Authorization Code Grant Flow >...." to get the associated client_ID and password_ID > to put in HA configuration.yaml "home connect..." . Do you understand what is missing in my process ?

**Comment by DavidMStraub** [comment]
Sorry but I don't understand. If you closely read all the readmes and similar issues people have submitted in the past, I'm sure you'll get it to work. If not, at the very least you have to provide detailed information about your settings on the HA and HC sides.

**Comment by erd82** [comment]
> Think I figured it out, somehow it adds ":443" to my redirect uri. removing that sends to log in to the HC portal. now figure out how to allow myself access
> 
> Ok, adding :443 in the redirect uri fixed that.
> 
> Now I am stuck with this, added my own username as default for testing, but no luck
> 
> **"The given user is not assigned to this app in the developer portal."** reported back by the portal..

@harkoprinssen: The reason why you were getting the message is, that you have not defined your email address (that you are using in your Home Connect App) in the "Home Connect User Account" of your Home Connect developer account. 

Hope this also helps others ... I have spend a few hours time to find this simple solution.

**Comment by samhed** [comment]
These instructions say we should use the internal url: https://www.home-assistant.io/integrations/home_connect/

For me, the solution was to specify my external url in the app settings on developer.home-connect.com.
