### ISSUE TITLE
Hob not implemented

### ISSUE THREAD

**Issue by PawelTroka** [DavidMStraub/homeassistant-homeconnect#20]
Would be great to implement Hob as well :)

**Comment by DavidMStraub** [comment]
I agree, especially since I have one!

But according to the API docs [this does not seem to be supported just yet](https://developer.home-connect.com/docs/cooktop/supported_programs_and_options), or did that change?

**Comment by PawelTroka** [comment]
@DavidMStraub Aaaa, ok, I see. I thought that since simulated API client mentioned it in available authorizations (as Hob-Monitor, Hob-Control, Hob-Settings, Hob) it is already supported.

**Comment by DavidMStraub** [comment]
Indeed I noticed that there is some info about the Hob on the API. I pushed some code to implement it. In my case, I cannot control anything, but when I switch it on manually, the `Cooking.Hob.Program.PowerLevelMode` program switches on; not too useful but more than nothing.

**Comment by DavidMStraub** [comment]
Let me close this for now, I guess more functionality can be added once the API supports it.

**Comment by PawelTroka** [comment]
Goood call, thanks a lot! GJ!
