### ISSUE TITLE
Operation state and fridge settings implementation request

### ISSUE THREAD

**Issue by sierraalpha83** [DavidMStraub/homeassistant-homeconnect#22]
Hi.

I think the operation state is not implemented yet this will be a great feature.
https://developer.home-connect.com/docs/status/operation_state

And the available fridge setting also.
https://developer.home-connect.com/docs/api/settings/fridgetemperature
https://developer.home-connect.com/docs/api/settings/fridgesupermode
https://developer.home-connect.com/docs/api/settings/freezertemperature
https://developer.home-connect.com/docs/api/settings/freezersupermode

**Comment by DavidMStraub** [comment]
Hi,

operation state is currently used in the appliance switch: if PowerState is `On` or OperationState is `Ready`, the switch is on:
https://github.com/DavidMStraub/homeassistant-homeconnect/blob/master/custom_components/homeconnect/switch.py#L96-L114

But perhaps adding the actual value of OperationState to the attributes would be what you mean?

Concerning settings: at the moment it is not possible to change  settings, but I wanted to implement service calls to directly talk to the API. That would solve this I think. Let me open a separate issue on that.

**Comment by DavidMStraub** [comment]
Related: #16, #23

**Comment by sierraalpha83** [comment]
> Hi,
> 
> operation state is currently used in the appliance switch: if PowerState is `On` or OperationState is `Ready`, the switch is on:
> https://github.com/DavidMStraub/homeassistant-homeconnect/blob/master/custom_components/homeconnect/switch.py#L96-L114
> 
> But perhaps adding the actual value of OperationState to the attributes would be what you mean?
> 
> Concerning settings: at the moment it is not possible to change settings, but I wanted to implement service calls to directly talk to the API. That would solve this I think. Let me open a separate issue on that.

Hi,

oh ok. Is the finished state implemeted? Can't find it in the file.

**Comment by JakobTewes** [comment]
Hey David,

would also love, if the fridge related parts could be implemented :-)

Thanks,

Jakob

**Comment by DavidMStraub** [comment]
Can you log the API stream of your fridge? Don't have one myself.

**Comment by JT089** [comment]
I‘ll give my best. What do I have to do? As I’m no developer, please start at a low level :-)

**Comment by motaker** [comment]
Hi, I would like to help also. 
I have home connected KGN36HI32(Fridge freezer) and SMV88TX36E(Dishwasher), TI9573X1RW(Coffee Machine).
Coffee Machine and Dishwaster I can control via home assistant(also via homekit) as I want but I have only ON/OFF switch for Fridge freezer.

Is it possible to implement below ?
- Fridge Temperature setting 2 to 8 degC
- Super cooling mode, on/off
- Freezer Temperature setting -24 to -16 degC
- Super freezing mode, on/off
- Fridge Camera ? (I suppose it is not supported in developer program ?)
![Capture](https://user-images.githubusercontent.com/40581042/64112278-45647000-cd87-11e9-850a-74529f5f9bb4.PNG)

**Comment by ecsfang** [comment]
Hi,
I could also help out if needed.
I have a hood, and there I would like to be able to eg check and turn on/off the lighting (both the normal light as well as the ambient light).
There are settings API for this, but I can't see that this is enabled in this component.
Best wishes,
Thomas

**Comment by DavidMStraub** [comment]
Thanks! I am aware I have neglected this over the last couple of months, but I plan to get back to it (and hopefully even turn it into a PR) soon.

**Comment by santoshkrishnanr** [comment]
Hello, is it possible to control Home Connect appliances just by using Python script  or installation of Homeassistant is necessary?

**Comment by DavidMStraub** [comment]
The HA implementation is based on a standalone package I also wrote: https://github.com/DavidMStraub/homeconnect

**Comment by DavidMStraub** [comment]
I am tidying up old issues and think this can be closed as the operation state should be tracked by #16 and the fridge settings by #23.
