### ISSUE TITLE
homeconnect.api.HomeConnectError: {'key': 'invalid_token', 'description': 'The access token is revoked'}

### ISSUE THREAD

**Issue by marrobHD** [DavidMStraub/homeassistant-homeconnect#24]
homeconnect.api.HomeConnectError: {'key': 'invalid_token', 'description': 'The access token is revoked'} I have settit up at this time. I want to have my dishwater into hass

**Comment by DavidMStraub** [comment]
Can you delete `.homeconnect-token-cache.json` in the HA config dir and try again?

**Comment by marrobHD** [comment]
When I clicked on Authorize, the configure entity disappeared. Without me clicking the confirmation button in homeassistant

**Comment by DavidMStraub** [comment]
That's actually normal. Did any entities appear?

**Comment by marrobHD** [comment]
No

**Comment by DavidMStraub** [comment]
Did you get it to work eventually?

**Comment by DavidMStraub** [comment]
Closing since the authentication has been rewritten using config flow.
