### ISSUE TITLE
getting the 500 internal server error

### ISSUE THREAD

**Issue by marcelwestrahome** [DavidMStraub/homeassistant-homeconnect#27]
mm getting the internal server error during initializing after removing the json file.
I get the login screen of home connect but afterwards this error:
https://xxx.nl/api/homeconnect?error=temporarily_unavailable&error_description=Internal+backend+service+currently+not+available&state=FXR2SoCxIQ4ycYvEipPt1LAH80X98R

**Comment by DavidMStraub** [comment]
I think this is a problem with the API server being temporarily down.

**Comment by marcelwestrahome** [comment]
Mm, you are right just worked today

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
