### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by dk-tommyt** [DavidMStraub/homeassistant-homeconnect#28]
hi.
trying to get this to work.
after a little struggling i have now com to 

in Home assistant i get

**Invalid config
The following components and platforms could not be set up:

homeconnect**

and if i press "homeconnect it links to 
https://www.home-assistant.io/components/homeconnect/

and i gets 

**Page Not Found

Looks like you've followed a broken link or entered a URL that doesn't exist on this site.**

> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homeconnect/__init__.py", line 49, in setup
    from homeconnect import HomeConnect
ImportError: cannot import name 'HomeConnect' from 'homeconnect' (/config/homeconnect/__init__.py)

> 
some help ?
grettings
tommy

**Comment by dk-tommyt** [comment]
![screenshot 6](https://user-images.githubusercontent.com/53595660/62416162-d8e63c00-b635-11e9-9bde-2abe2f361dde.jpg)
![screenshot 7](https://user-images.githubusercontent.com/53595660/62416163-dd125980-b635-11e9-9b93-1e150218788c.jpg)
![screenshot 8](https://user-images.githubusercontent.com/53595660/62416164-df74b380-b635-11e9-9dbd-82229c656798.jpg)
![screenshot 9](https://user-images.githubusercontent.com/53595660/62416166-e3083a80-b635-11e9-88f3-6432c716908d.jpg)

**Comment by dk-tommyt** [comment]
here is  picture of what happen 
pic 2 : it is the URL that is wrong"redirect_uri=http%3A%2F%2F1" 
and when i write url instead of uri then pic 3 is coming.
when i press " approve" then pic 4.
grettings
tommy

**Comment by DavidMStraub** [comment]
You have a local non-https URL (192...) in the first pic, while the redirect URI leads to a https .dk address. What is the `base_url` in your HA config? What is your redirect URI? The error message means that there is something not configured correctly in one or the other. Please double-check the Readme (and similar issues).

**Comment by dk-tommyt** [comment]
Hi David.
it was a foul 40 :o). 40 cm from the screen 
my ip was closed for inbound traffic by my isp

now it is working.
V. homeassistant/raspberrypi4-64-homeassistant with version 0.97.0b2 

grettings
tommy
