### ISSUE TITLE
Is it possible to create a own Program?

### ISSUE THREAD

**Issue by MiguelESP89** [DavidMStraub/homeassistant-homeconnect#29]
Hey i wanted to know if it is possible to create a own or customize program. 
For examle a double espresso or a stronger coffee. 

If yes, how can i create one? 

Thanks for the help

Regards
Miguel

**Comment by DavidMStraub** [comment]
Sorry, I somehow overlooked this issue.

This would require making it possible to set options via service calls in HA. This is something I would like to have, but it's not implemented yet.

So I will close this issue, but keep it in mind.
