### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by anthonyangel** [DavidMStraub/homeassistant-homeconnect#3]
I'm trying to run this on hassio, but have SSL enabled via a reverse proxy (Caddy), my site is accessible via the internet at https://hasstest.domain.com, but trying to access the /api/homeconnect endpoint gives me the following error
```
500 Internal Server Error
Server got itself in trouble
```

The error log in hass when I try and complete the auth flow shows
```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/http/static.py", line 66, in staticresource_middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/http/real_ip.py", line 34, in real_ip_middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/http/auth.py", line 107, in auth_middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/http/view.py", line 115, in handle
    result = await result
  File "/config/custom_components/homeconnect/__init__.py", line 123, in get
    self.hc.get_token(str(request.url))
  File "/config/deps/lib/python3.6/site-packages/homeconnect/api.py", line 95, in get_token
    client_secret=self.client_secret)
  File "/usr/local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 187, in fetch_token
    state=self._state)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/web_application.py", line 174, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 221, in parse_authorization_code_response
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
```

I'm assuming that this is to do with SSL being terminated at the proxy rather than on the hass box

**Comment by DavidMStraub** [comment]
Oh, I see.

Can you try if it works when you add

```python
import os
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
```
at the beginning of `custom_components/homeconnect/__init__.py`?

**Comment by immert20** [comment]
Same also after the import os

**Comment by DavidMStraub** [comment]
I just checked on my own HA instance that is also behind an nginx proxy and it worked. Calling the `/api/homeconnect` endpoint directly, I also got a 500, but this is normal (after the login redirect, it is  called with additional parameters).

Can you please double check that you have `https://hasstest.domain.com/api/homeconnect` listed as one of the valid Redirect URI  in your Home Connect app's settings? Perhaps you accidentally put http there?

**Comment by DavidMStraub** [comment]
OK - that means that the authentication indeed succeeded (I also have the problem with the blank window and sometimes downloaded file, not sure how  to get rid of it. Indeed I copied most of the code for that from the Spotify component).

Concerning the absence of devices, I assume you have added them to your Home Connect account (using the Android app), right? Are there any errors in the HA log?

**Comment by immert20** [comment]
Where do you read out the URL for Authorising? Mine url show my internal IP address.. When I edit the URL for authorise I can login with my HomeConnect credentials en get the 500 error. But when I click on Successful authorised nothing happen..

**Comment by DavidMStraub** [comment]
@immert20, so you are being shown the Home Connect login screen? This is good, because it means the redirect URI is being accepted. Then when you are done authorizing, you are getting a 500 server error, do I understand correctly?

If so, can you please check if there is any error showing in your `home-assistant.log`?

**Comment by immert20** [comment]
@DavidMStraub Yes I get that, but only after edit the url manually.. because there is an internal ip filled in. I don't know where that $vars is coming from.

**Comment by DavidMStraub** [comment]
It is taken from `hass.config.api.base_url`. Can you please try adding the "correct" host name/IP in your HA config like

```yaml
http:
  base_url: https://HOST:PORT 
```

**Comment by anthonyangel** [comment]
@immert20 Sounds like you need to set your [base_url](https://www.home-assistant.io/components/http/) parameter of the http component (and prefixing it with https)

**Comment by immert20** [comment]
Yes it works!! But I tried to switch on my Coffee machine from HASS, but it won't turn on

**Comment by DavidMStraub** [comment]
Indeed, the power on/off switches don't work for me either (also using raw API calls) and I don't know why.

Are you able to brew coffee though, once switched on manually and acticating remote start?

**Comment by immert20** [comment]
Hmm that's weird. I will check that tonight!

**Comment by dvbit** [comment]
Same issue.
Behind nginx reverse proxy.
base url: https>mydomain.it
certificate by letsencrypt

blank screen

**Comment by FlavorFx** [comment]
same issue here.
no reverse proxy
base url set (https)
certificate by letsencrypt
home connect url set
home connect login succeeded
blank screen
when I refresh error 500
I also deleted homeconnect token cache and retried but no improvement.

**Comment by DavidMStraub** [comment]
Any error in the log?

**Comment by DavidMStraub** [comment]
By the way I received an e-mail from the Home Connect Developer Program yesterday mentioning that they have some problems with the API due to increased traffice after relaunching their mobile app. So it might just be that the server was down.

**Comment by FlavorFx** [comment]
I retried once again today but same behavior. I was able to enter home connect, agreed on access to my components, but after browser update blank screen.

<img width="391" alt="Bildschirmfoto 2019-11-01 um 19 23 07" src="https://user-images.githubusercontent.com/19329488/68047648-321a4600-fcdf-11e9-94a9-14dfecb67ecd.png">

This is my log:
_Log Details (WARNING)
Fri Nov 01 2019 19:22:40 GMT+0100 (CET)
Unexpected value for HomeConnect door state: {}_

BTW: Yesterday after some time I saw my washing machine components but after reboots it was gone.

**Comment by AleXSR700** [comment]
Hello everyone,
I seem to have the same problem. I am trying to install Home Connect and I used 
`http://192.168.0.224:8123/auth/external/callback`
as Redirect URI.
I can login when I hit "Open Website" and then when I confirm that I want to grant access to everything, I get the error 
`500 Internal Server Error
Server got itself in trouble `

Any idea what could be causing this or what to try to fix it?
