### ISSUE TITLE
Config flow not working

### ISSUE THREAD

**Issue by anthonyangel** [DavidMStraub/homeassistant-homeconnect#37]
Hi, thanks for all the recent work which you've put into this.

I'm unable to authenticate via the the new config flow integration, I get the following error when I try to add the Home Connect integration.

![Screenshot_20191120-092632](https://user-images.githubusercontent.com/2271981/69226381-f7862980-0b77-11ea-9826-98627245bdac.png)

I'm running home assistant 102.0b2, have your component installed via HACS (the current code in the master branch) and have updated the callback URL in the home connect developer site as per the docs.

I'll enable more verbose logging, as I currently have no more useful information to look into this.

**Comment by DavidMStraub** [comment]
Have you been able to install it in HACS without changes? I just tried it out and the INSTALL button is greyed out (this is HACS 0.17.3 on HA 102.0b2).

**Comment by DavidMStraub** [comment]
Nevermind. Thhe initial load of HACS just took *very* long, then the button appeared.

**Comment by DavidMStraub** [comment]
So, for me it's working, actually.

Can you please try the newest commit? There was an unhandled error that you might have hit.

**Comment by anthonyangel** [comment]
This was PEBCAK on my part, I assumed that if I was using the new Config Flow integration then I wouldn't have to still add `homeconnect:` to my configuration.yaml file.

It now works for me when I follow the instructions 🤦‍♂, I added the below to my configuration.yaml file and then when I try to add the integration I can follow the link to the Home Connect API site and authorise the integration
```
homeconnect:
  client_id: YOUR_CLIENT_ID
  client_secret: YOUR_CLIENT_SECRET
```

Is there a way to remove the requirement for amending the configuration.yaml file and adding this in its entirety through the config flow?

**Comment by DavidMStraub** [comment]
Good question, not sure. I was following the instructions of the new native HA OAuth2 flow:
https://developers.home-assistant.io/docs/en/api_lib_auth.html
As far as I can see this is currently only used by the [Somfy](https://www.home-assistant.io/integrations/somfy/) component and there the `configuration.yaml` entry is still mentioned in the docs.
