### ISSUE TITLE
Assign entities to Home Assistant devices

### ISSUE THREAD

**Issue by FuX-STV** [DavidMStraub/homeassistant-homeconnect#39]
Hello

The Device List are empty. can you check this?
![image](https://user-images.githubusercontent.com/13559033/69242140-80b15680-0ba0-11ea-93d8-3036d65879dd.png)

Version homeassistant-homeconnect: a6bbdf4
Version Home Assistant: 0.102.0b2

Thanks

**Comment by DavidMStraub** [comment]
Can you check if restarting HA helps?

**Comment by FuX-STV** [comment]
it seems not better :/

**Comment by FuX-STV** [comment]
its my first installation of that component... 
that restart workaround does not work

**Comment by anthonyangel** [comment]
My device list in integrations is empty, but the resources have been added and I can view in the states page or in the UI

**Comment by FuX-STV** [comment]
ohhh lol... sorry for that..

**Comment by DavidMStraub** [comment]
Oh I see. But this is actually a good point because it means I still need to properly assign the entities to HA devices.
