### ISSUE TITLE
HACS support?

### ISSUE THREAD

**Issue by espizo** [DavidMStraub/homeassistant-homeconnect#44]
Thank you so much for creating this integration!

I see there is a hacs.json file in this repo, but I can't seem to find this integration in HACKS/Community in my Homeassistant page.

Am I missing something?

**Comment by DavidMStraub** [comment]
You're right, I forgot to submit it as a default integration in HACS, will do it.
In the meantime, you can also just add it as a custim repository, that works.
And the PR in Home Assistant is under review.

**Comment by aee74** [comment]
I tried to use the custom integration. I use duckdns. I also created the needed homeconnect API keys. After that I don't see any newe sensors or HA.
Do I still need to install the integration?
i tried this but than HA says it needs to open a website. Then I login to the devoloper site and accept. The site comes with a return "500 Internal Server Error
Server got itself in trouble "

Any suggetions?

**Comment by DavidMStraub** [comment]
This looks like either the redirect URI or the `base_url` is wrong. Please read the instructions carefully again.
