### ISSUE TITLE
Bekomm es einfach nicht ans Laufen

### ISSUE THREAD

**Issue by Marvilius** [DavidMStraub/homeassistant-homeconnect#46]
Hallo!

Hab die Komponente mittels HACS installiert

in configuration.yamhl steht unter base url https://famxxxxx.duckdns.org:8123

Ich kann auch per app drauf zugreifen, also der https über duckdns läuft

ruf ich die adresse inkl /auth/external/callback auf kommt folgende Meldung:

Missing code or state parameter in https://famxxxxxxxx.duckdns.org:8123/auth/external/callback

in der configuration.yaml hab ich homeconnect drin und sowohl client id und secret aus der siemens app übernommen.

Leider kommt bei mir aber keine  entity daher

Kann mir wer helfen?

**Comment by DavidMStraub** [comment]
Hi,

Dass das direkte Aufraufen nicht geht ist so schon korrekt (die Callback-URL ist nur zur Verarbeitung des in den URL-Parametern codierten Tokens da).

Kommt irgend etwas im Log? Falls in der Konfiguration etwas nicht stimmt, sollte ein Fehler im Log auftauchen.

Um auszuschließen, dass aus irgend einem Grund gar keine Geräte erkannt werden, kannst du auch mal direkt das Python-Paket ausprobieren mit diesem Snippet: https://community.home-assistant.io/t/home-connect-alpha-testers-wanted/82603/116

**Comment by Marvilius** [comment]
Hallo!

Hab es nun doch geschafft es ans Laufen zu bekommen! Witziger Hintergrund: Auf meinem Mac mit Safari ging es nicht, weil beim Installieren der Link nur auf einer Fehlerseite landete. An einem Windows PC mit Firefox Browservaber leitete es mich auf die Anmeldeseite der API weiter. Dort angemeldet, konnte ich dann zulassen. Und nun geht fast alles. Ausser dass Restlaufzeiten und Programmfortschritt nicht stimmen....
