### ISSUE TITLE
Problems with setup

### ISSUE THREAD

**Issue by Heiner1967** [DavidMStraub/homeassistant-homeconnect#48]
Hi,

I installed HACS and it works for another component, then I add your Homeconnet.
I have a Siemens Dishwasher fully visible in the Home Connect App on my phone.
I create this developer  and application on the Home Connect Developer page and took the relevant code and the URL as per my configuration.yaml file which looks like this:

`http:
       base_url: hassio.local:8123  (3 spaces in the beginning of this line)

homeconnect:
      client_id: 7B55.....                  (3 spaces in the beginning of this line)
      client_secret: FA77...            (3 spaces in the beginning of this line)`

The good thing is I have nothing in my Error Log after reboot. The bad thing is that I still don@t recognise my dischwasher in Homeassistant. Do I need to configure it on top somewhere somehow? Sorry but I do miss  this in the descriptions.

kind regards

**Comment by DavidMStraub** [comment]
Hi,

looks OK, except that I'm not sure it works if your `base_url` doesn't start with `https://`. Do you have the `https://` at the beginning of your redirect URI?

Also, did you add the integration under the "integrations" panel in HA after restart?

**Comment by Heiner1967** [comment]
Hi,
that within the http section I have to mention https did not soud logic, hence I did it as per above.
Within home connect developer Application the redirect URL is:
https://hassio.local:8123/auth/external/callback

**Comment by DavidMStraub** [comment]
Can you reach your instance under `https://hassio.local:8123`? If not it won't work.

**Comment by Heiner1967** [comment]
Hi, within my home network, yes. I think this is anyhow the default local address.
but from Internet no, here I would need to change to get a dns Adress plus opening the firewall for the port and incoming connection, not sure this is needed?

**Comment by DavidMStraub** [comment]
>  think this is anyhow the default local address.

No, only if you have configured SSL.

> not sure this is needed?

No its not.

**Comment by Heiner1967** [comment]
Hi,

https://hassio.local:8123 is not working in my home network
http://hassio.local:8123 is working in my home network.
I amended in configuration.yaml to
`
http:
   base_url: http://hassio.local:8123
`
and on the developer side of home connection to 
`http://hassio.local:8123/auth/external/callback`

after reboot i see in the log:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method`

**Comment by DavidMStraub** [comment]
Quote from the Readme:

> it will not work without https, but your Home Assistant instance does not have to be accessible from the internet and a self-signed certificate will do

**Comment by Heiner1967** [comment]
Hi, meanwhile i added SSL to my installation and I am able to access 

https://xxx.duckdns.org:8123

and this entry is in configuration.yaml as:
http:
   base_url: https://xxx.duckdns.org:8123
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem
and in the homeconnect developer application as
 https://xxx.duckdns.org:8123/auth/external/callback

The good thing is that i do  not get a error meassage anymore, but unfortuniatly, i do not see my registered dishwasher either in home assistant.

Where would it need to show up: under "known_devices.yaml"?

Thanks for your help

**Comment by Heiner1967** [comment]
solved, I missed the point in editing the integration part. here now homeconnect was available and found my dishwasher.

Many Thanks. super cool.

**Comment by Heiner1967** [comment]
obviously problem is solved
