### ISSUE TITLE
Use real available programs instead of a fixed list

### ISSUE THREAD

**Issue by Ligio** [DavidMStraub/homeassistant-homeconnect#53]
Since there is an endpoint ( /homeappliances/{haid}/programs/available ) to get the list of available programs, it would be nice to use it instead of a fixed one:

 https://github.com/DavidMStraub/homeassistant-homeconnect/blob/a887d97583bc98eccd311320b88218e3f43646c6/custom_components/homeconnect/api.py#L163

**Comment by SeraphimSerapis** [comment]
This would be awesome for coffee programs that go beyond standard things like Espresso or Coffee -- e.g. Americano, Ristretto usw. Those could also be exposed via a service if it's too much of a hassle to create a switch for each item on that list.

**Comment by Krocko** [comment]
Yes, that would be very cool. 
But I vote for the switch.

**Comment by monster400** [comment]
So that´s why i dont have the option to control the lights of my hood yet?

**Comment by DavidMStraub** [comment]
No, that's #57.

**Comment by DavidMStraub** [comment]
Unfortunately using the available programs is not possible at present since they cannot be queried when the appliance is off. So the solution to this IMO are service calls, #23, so I close this issue.
