### ISSUE TITLE
HACS integration

### ISSUE THREAD

**Issue by puytr** [DavidMStraub/homeassistant-homeconnect#54]
Dear David,
Thank you very much for your efforts to get this custom component to work in Hassio. Today I've reinstalled HACS and installed your HomeConnect custom component. After following steps 1 through 5 from the instructions, I go to Integrations to get the HomeConnect component started. The first time it took a long time before a screen came back with the message 'Aborted'. Now, no matter how often I try to delete and reinstall, the same message keeps coming back. There is no error in the log files and the Home Assistant components remains red (not configured) in HACS. 

Any direction is very much appreciated.

**Comment by DavidMStraub** [comment]
Unfortunately I'm not a HACS expert and I suspect that this is a problem on the HACS side. Can anyone reproduce this problem?

**Comment by puytr** [comment]
Hello David,
I've installed a vanilla version of Hassio. Next, I've installed the following add ons: DuckDNS (for ssl), Configurator (to edit the configuration.yaml). With this up and running, the following step was to install the HACS store. This all worked. 

So, now back to Home Connect:
1. Registering the App on the Home Connect Developer website.
2. Configuring homeconnect (with client_id and client_secret) in configuration.yaml
3. Restart Hassio in order to re-initialize.
4. No errors in the log (amazing!)
5. Connection Home Connect via Integrations.
6. The external website Home Connect opens and asks for credentials.
7. You have to authorize ALL the functions that you wish to access (click Accept).
8. An error message: **The site can't be reached**.

Ad. 8 My redirect URL is https://XXX.duckdns.org:8123/auth/external/callback
This is exactly what I've pasted in my http component in configuration.yaml
note: the XXX hides my real duckdns domain.

So, almost there. One last step which I need to be figured out.

Cheers,
Richard

**Comment by SeraphimSerapis** [comment]
@puytr Do you need the port to access your installation? I skipped using my port (since my domain already points at the right port anyway) and the installation via HACS works flawlessly.

@DavidMStraub I installed via HACS two days ago and see no issues with the installation. Everything works as expected.

**Comment by puytr** [comment]
@SeraphimSerapis @DavidMStraub Success! After trying to figure out why it doesn't work, I went back to basic SSL reconfiguration. By re-installing DuckDNS and manually configuring http and home connect in configuration.yaml, the installation worked straight away. I'm now testing with my ceiling hood, coffeemachine, cooking plate and oven.  Keep up the good work David!
