### ISSUE TITLE
Hood Light controll

### ISSUE THREAD

**Issue by jarnojlaine** [DavidMStraub/homeassistant-homeconnect#57]
Ok, the only reason I wanted to connect my hood to HA was for lighting control. Now I've got i connected, BUT there is no switch for the light...

under `switch.hood` 
I see attributes

local_control_active: false 
operation_state: inactive
remote_control_active: true 
remote_control_start_allowed: true 
power_state: off 
lighting: false 
lighting_brightness: 10 
active_program: null 
venting_level: fan_stage02 
intensive_level: intensive_stage_off 
elapsed_program_time: 0 
friendly_name: Hood

What can I do to get the light control as a separate entity?

**Comment by DavidMStraub** [comment]
Can you switch it with the Home Connect app?

My own hood is dumb, unfortunately.

**Comment by ecsfang** [comment]
Hi, jumping in from the side ... ;)
I have a hood as well (Neff D96IKW1S0), with "background" light, which I hope to be able to control from from HA.
Using the "Home Connect" app, I can control, not only on/off but also select color and dim the light.
If I could help with some kind of log, I could try do that.
Best regards,
Thomas

**Comment by DavidMStraub** [comment]
Hi,

very interesting. Yes we would need to know what the event stream reports on state changes of the light, as well as collect the relevant API end points from the Home Connect documentation. It would be great if you could help there.

**Comment by ecsfang** [comment]
I guess that the API is described, e.g. the Ambient Light ("backlight") is described by https://developer.home-connect.com/docs/api/settings/ambientlight.
What kind of log could I help with? If you point me in the right direction, I could fiddle with the Home Connect app and take some logs.

**Comment by jarnojlaine** [comment]
> 
> 
> Can you switch it with the Home Connect app?
> 
> My own hood is dumb, unfortunately.

I can it's dimmable by 10% increments. Can't seem to be able to figure out the setup.

**Comment by Sjack-Sch** [comment]
Hi David,
Adding light control for the hood would be amazing.

For my hood the following:

GET /homeappliances/{haid}/settings
gives:
{
  "data": {
    "settings": [
      {
        "key": "BSH.Common.Setting.PowerState",
        "value": "BSH.Common.EnumType.PowerState.Off",
        "name": "Power status",
        "displayvalue": "Off"
      },
      {
        "key": "Cooking.Common.Setting.Lighting",
        "value": false,
        "name": "Work light"
      },
      {
        "key": "Cooking.Common.Setting.LightingBrightness",
        "value": 10,
        "unit": "%",
        "name": "Brightness"
      }
    ]
  }
}

To switch the light on/off:
PUT /homeappliances/{haid}/settings/Cooking.Common.Setting.Lighting
with:
{
  "data":
      {
        "key": "Cooking.Common.Setting.Lighting",
        "value": true, ####  true/false
        "name": "Work light"
      }
}

To change the LightingBrightness:
PUT /homeappliances/{haid}/settings/Cooking.Common.Setting.LightingBrightness
with: 
{
  "data":
      {
        "key": "Cooking.Common.Setting.LightingBrightness",
        "value": 40,  ### any value between 10 -100
        "unit": "%",
        "name": "Brightness"
      }
}

**Comment by Sjack-Sch** [comment]
> Hi,
> 
> very interesting. Yes we would need to know what the event stream reports on state changes of the light, as well as collect the relevant API end points from the Home Connect documentation. It would be great if you could help there.

Hi David,
Adding light control for the hood would be amazing.
I installed a Bosch hood recently and played with the https://apiclient.home-connect.com.
See below some commands and responses of my Bosch hood that might help.

GET /homeappliances/{haid}/settings
gives:
{
"data": {
"settings": [
{
"key": "BSH.Common.Setting.PowerState",
"value": "BSH.Common.EnumType.PowerState.Off",
"name": "Power status",
"displayvalue": "Off"
},
{
"key": "Cooking.Common.Setting.Lighting",
"value": false,
"name": "Work light"
},
{
"key": "Cooking.Common.Setting.LightingBrightness",
"value": 10,
"unit": "%",
"name": "Brightness"
}
]
}
}

To switch the light on/off:
PUT /homeappliances/{haid}/settings/Cooking.Common.Setting.Lighting
with:
{
"data":
{
"key": "Cooking.Common.Setting.Lighting",
"value": true, #### true/false
"name": "Work light"
}
}

To change the LightingBrightness:
PUT /homeappliances/{haid}/settings/Cooking.Common.Setting.LightingBrightness
with:
{
"data":
{
"key": "Cooking.Common.Setting.LightingBrightness",
"value": 40, ### any value between 10 -100
"unit": "%",
"name": "Brightness"
}
}

**Comment by Sjack-Sch** [comment]
I adapted switch.py (see attached) to add light on/off control for the hood. It is a dirty hack, but it works.
I think it is better to have light control using the light platform instead of the switch platform, I suppose the light brightness could be controlled from the light platform too.
I created a light.py that would add the light control as a light entity to HA, however it seems home assistant never activate this file. I think I need some guidance here

[switch.py.zip](https://github.com/DavidMStraub/homeassistant-homeconnect/files/4950004/switch.py.zip)

**Comment by DavidMStraub** [comment]
Thanks @Sjack-Sch! Make sure you add `"light"` to this list when you add a `light.py`:

https://github.com/DavidMStraub/homeassistant-homeconnect/blob/master/custom_components/home_connect_beta/__init__.py#L68

I suggest you submit a pull request with your changes, then we can work to improve it if necessary!

**Comment by DavidMStraub** [comment]
Feature added by @Sjack-Sch! Please report success or issues here. Thanks!

**Comment by llevering** [comment]
> Feature added by @Sjack-Sch! Please report success or issues here. Thanks!

Works great with a Siemens LR97CAQ20 hood

**Comment by GrumpyMeow** [comment]
Works also with Siemens LC97FVW60S

**Comment by DavidMStraub** [comment]
Awesome, I think we can close this issue :+1: 

@Sjack-Sch do you plan to submit this to HA core now or only after implementing brightness?

**Comment by DavidMStraub** [comment]
Oh dear, I missed your PR :scream: Sorry...

**Comment by Sjack-Sch** [comment]
No worries 👍

**Comment by monster400** [comment]
Hey, is this submitted to the official home-assistant core build?

I got a LR29CQS25

**Comment by DavidMStraub** [comment]
Nope

**Comment by monster400** [comment]
@DavidMStraub where can i see if a fix is submitted or not?

**Comment by DavidMStraub** [comment]
Not sure what you mean, you ca compare the source code.

**Comment by Sjack-Sch** [comment]
This feature is now part HA Core.
