### ISSUE TITLE
A way to bypass the SSL difficulty?

### ISSUE THREAD

**Issue by YRRK** [DavidMStraub/homeassistant-homeconnect#58]
Hi David,

Is there a way to make it more simple? For standard users, as me, it's bit difficult to get SSL enabled constructed on a "normal" home assistant installation. I run in all sort of troubles and make things more complex than needed.

If I take a look at the Home Connect plugin from ioBroker (a sort of Home Assistant, it's pretty amazing complete!) they have a simpler authentication proces using device flow. See:

https://www.iobroker.net/#en/adapters/adapterref/iobroker.homeconnect/README.md

https://translate.google.com/translate?hl=en&sl=de&tl=en&u=https%3A%2F%2Fgithub.com%2Fdna909%2FioBroker.homeconnect

This works the same way!

The thing is... ioBroker is somewhat different as Home Assistant, I could like to keep just 1 master system wich is HomeAssistant. And I tried bypass this "problem" to connect HomeConnect from ioBroker > to Homekit (via their YAHKA bridge) and then to Home Assistant. But this coupling doesn't work flawless. (Only 1 device comes trough, not all 3 of my HomeConnect devices, so that's a pity).

So either way, I can't get my Home Assistant working the easyway.
Would it be possible for you to take a look the authentication proces to make it as easy as with ioBroker's Home Connect? In their way you register an application, have the ID. And use that ID to make a call for a key(without https).
:-)

**Comment by DavidMStraub** [comment]
Hi,

I will not implement device flow: https://github.com/DavidMStraub/homeconnect/issues/2

BTW, you don't actually need SSL. In the past Home Connect used to require the redirect URI to start with `https`, but users have reported on the forums that this seems to be no longer necessary.
