### ISSUE TITLE
Install attempt 2, homeassist says: Aborted.

### ISSUE THREAD

**Issue by YRRK** [DavidMStraub/homeassistant-homeconnect#62]
Hi David,

I tried to install the homeconnect component again, this time via HACS.
I filled in the Redirect URI
base url set to my home assistant.
The well knowm config.yaml filled in with
homeconnect:
client_id: client id form dev site
client_secret: filled in the secret form de dev site

Reboot

Going to the integrations page, going to Home Connect. If I click it. It says: Aborted 
And that's it... nothing happends :-( 

Do you have any clue?

**Comment by peterPython92** [comment]
had this at first as well, I did a reload HASS after adding the ID / Secret and then it went fine - until the issue I just raised :)
