### ISSUE TITLE
Home Connect Developer Portal - can't grant access

### ISSUE THREAD

**Issue by peterPython92** [DavidMStraub/homeassistant-homeconnect#63]
Hi there,

when I try to set up the integration after installatin with HACS, the following error appears on the home connect portal:

"The given user is not assigned to this app in the developer portal."

In the URL, the client ID seems correct, also I double checked my login and it's correct. 

Any idea ? :)

Thanks

**Comment by DavidMStraub** [comment]
No, no idea. Please send an e-mail to the Home Connect support.

**Comment by DavidMStraub** [comment]
Can this be closed?
