### ISSUE TITLE
Remote start: any way to enable it by an API call?

### ISSUE THREAD

**Issue by Ligio** [DavidMStraub/homeassistant-homeconnect#67]
Do you know if there is an HC endpoint to enable "remote start"?
I have a dishwasher, but it's a pity since I can start a washing program only if I press a physical button before! I know it's not your fault, but I'm wondering if you haven't dug deeper into the subject to find a solution.
Thanks and really nice job with this integration!!!

**Comment by jacobstim** [comment]
I think this is a deliberate design choice, only to allow remote start after the user of the dishwasher approved it. When loading the dishwasher with dishes to clean, you are physically near the dish-washer and can enable it before you close the door (and then afterwards, you can remote enable the dishwasher to perform the cleaning). 

Given that the remote start is deactivated if you open the door, I suppose that the intended usage is not to have it "permanently active" to allow a remote start at any time ("for safety reasons"), such that a manual push of the allow remote start button is always required.

**Comment by DavidMStraub** [comment]
Yes indeed, this is why I'm afraid it will never be possible to activate "remote start" remotely. (And I also find it slightly annoying.)
