### ISSUE TITLE
Hood not implemented

### ISSUE THREAD

**Issue by anthonyangel** [DavidMStraub/homeassistant-homeconnect#7]
I temporarily threw in a load of additional logging to try and find out why I was authenticated, but got no devices, no logs and no errors.

I could see that I was receiving valid JSON back from the API, the first item received back was a hood, and there's nothing specified for a hood in the get_devices function, so it just goes to the `else: break` without returning anything.

I can imagine that there are 2 fixes to come for this:
- Handle an unsupported device more elegantly, with logging of the error, and continuing to load the supported devices
- Introduce support for a hood, this could be represented as a fan and a light in HA (I'm going to try and find time to put in a PR for this)

**Comment by DavidMStraub** [comment]
Good catch, thanks for debugging this. In fact both things should be done (and the first one is very simple).

**Comment by DavidMStraub** [comment]
@anthonyangel I just pushed initial support for a hood (it will just show the program switches for Automatic/Venting/DelayedShutoff). Since this is not present in the API simulator, I didn't test it though. Do you feel like giving it a try?

**Comment by carloscae** [comment]
Hood as a ventilator would be great. Could automate with a Humidity sensor.
I'm also missing lighting of the Hood. I could see myself automating it with a motion sensor.
Thanks guys!

**Comment by SergiSuarez** [comment]
Hello @DavidMStraub 
Just installed the custom component. I have a hood and an oven.
I can't switch on/off any of them.
I can see an error stating:
Error while executing bound method HomeConnectAppliance..... for both the oven and hood.
I can see switch and sensor but switches doesn't work and neither are updated.

Any information I can send you?

**Comment by DavidMStraub** [comment]
Hi,

what would be interesting to know:

- Can you switch them on from the Android app while they are switched off?
- Does the hood provide any additional sensor data in the API response (should be visible in the log) that could be used for a HA sensor?

It would also be useful if you paste the full error message. Thanks!

**Comment by DavidMStraub** [comment]
Hi,

the response `'HomeAppliance is offline'` is returned by the API, so this means it really was offline at HA startup. Apart from the on/off switch not working (this is tracked in #10), is there anything that works for you? (E.g. can you start programs on the hood afterswitching it on manually?)

**Comment by DavidMStraub** [comment]
Closing this (my hood is dumb so I cannot test whether the integration works).
