### ISSUE TITLE
Sensor remaining program time invalid date

### ISSUE THREAD

**Issue by Krocko** [DavidMStraub/homeassistant-homeconnect#73]
I get an invalid date error on the remaining program time sensor. 
![image](https://user-images.githubusercontent.com/29394115/80864303-15f16480-8c82-11ea-94c1-18fe6585cb23.jpeg)
![image](https://user-images.githubusercontent.com/29394115/80864306-1b4eaf00-8c82-11ea-817d-fb639f50f910.jpeg)

**Comment by DavidMStraub** [comment]
Can you please post the error from the log? Are you on the latest commit?

**Comment by Krocko** [comment]
There is no message in the log. I am on version 0.3.

**Comment by DavidMStraub** [comment]
But the date shown above is valid, no? Strange

**Comment by Krocko** [comment]
Maybe it is the format?
`2020-05-03 22:24:40+02:00` this format should be right?

**Comment by DavidMStraub** [comment]
But it's a `datetime.datetime` instance, so Home Assistant takes care of the formatting itself, there are no strings involved...

**Comment by Krocko** [comment]
I don‘t know. I am not an expert.

**Comment by motaker** [comment]
Hi I have same. The remaining time is not displayed in seconds.

![image](https://user-images.githubusercontent.com/40581042/80892335-79eb4b80-8cc9-11ea-9d71-c9cd9439c56a.png)

![image](https://user-images.githubusercontent.com/40581042/80892356-ad2dda80-8cc9-11ea-86b1-c15d731f6628.png)

![image](https://user-images.githubusercontent.com/40581042/80892395-fa11b100-8cc9-11ea-9750-72889c82f7c4.png)

**Comment by DavidMStraub** [comment]
Which HA version is this? Is it Lovelace UI? I don't think this is a problem of the integration. The UI has to take care of displaying the timestamp sensor as a countdown.

**Comment by motaker** [comment]
Hassio 0.109.2, 
HACS 0.24.3, 
Home Connect v0.3

**Comment by DavidMStraub** [comment]
It's a timestamp sensor and it displays a timestamp. It's supposed to be like that. If you add it to a lovelace entity card, it will display a countdown.

That there is no state history is strange but cannot be the integration's fault.

**Comment by h4nc** [comment]
From the release notes of v0.3

> The remaining program time sensor is converted to a timestamp sensor.

Could you explain what changed? So it's a timestamp now , but what was it before? Does the entity name stay the same?

**Comment by h4nc** [comment]
From the release notes of v0.3:

> The remaining program time sensor is converted to a timestamp sensor.

Could you explain what changed? So it's a timestamp now, but what was it before? Does the entity name stay the same?

**Comment by DavidMStraub** [comment]
Before it was a numeric sensor (remaining time in seconds).

This change was requested by Paulus as part of the PR discussion (https://github.com/home-assistant/home-assistant/pull/29214). The point is that it is much more efficient to store a countdown as a fixed point in time and handle the display by the UI, rather than having to update a sensor every second just to count down. This will also automatically deal with displaying the right time units (hours or minutes or seconds), which solves an earlier issue #35. It will also count down continuosly rather than having to wait for the API to report progress.

If it works correctly, that is :wink:

**Comment by DavidMStraub** [comment]
OK, my bad. It should return an ISO-formatted string, not a `datetime` instance. In my case, it worked anyhow, but possible changing that will fix it for you as well.

**Comment by Krocko** [comment]
With beta version 1.0.1 I got the following error in the log:
```
Logger: homeassistant.helpers.entity
Source: custom_components/home_connect_beta/sensor.py:65
First occurred: 9:19:31 (4 occurrences) 
Last logged: 9:19:34

Update for sensor.kaffeemaschine_remaining_program_time fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/home_connect_beta/sensor.py", line 65, in async_update
    and self._state < dt_util.utcnow()
TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'
```

**Comment by DavidMStraub** [comment]
Oh! This is a bug that will break the official integration as well. It was introduced because the output was changed from `datetime.datetime` to `str`, but the comparison wasn't changed.

Do you have time to test the following modification: In line 65 of `sensor.py`

```python
and dt_util.parse_datetime(self._state) < dt_util.utcnow()
```

That would be super helpful as I can't test it right now. Thanks!

**Comment by Krocko** [comment]
The error message is gone with this line, but I can test it only when I am at home later today.

**Comment by DavidMStraub** [comment]
Great! If it works, feel free to submit a PR directly to HA Core!

**Comment by Krocko** [comment]
Hehe no no. 😄

**Comment by h4nc** [comment]
I had the same issue (invalid date in Lovelace) but I just noticed that it works fine now. 

However I can't tell if updating to 0.110.4 or switching to the core version of this integration a few days ago (or even something else) fixed this. 

So I think this can be closed.
