### ISSUE TITLE
SDK.Error.HomeAppliance.Connection.Initialization.Failed

### ISSUE THREAD

**Issue by allmoney** [DavidMStraub/homeassistant-homeconnect#75]
In log I found this error:

Logger: custom_components.homeconnect.switch
Source: custom_components/homeconnect/switch.py:138
Integration: Home Connect (documentation)
First occurred: 11:44:14 AM (1 occurrences)
Last logged: 11:44:14 AM

Error while trying to turn off device: {'key': 'SDK.Error.HomeAppliance.Connection.Initialization.Failed', 'description': 'HomeAppliance is offline'}

Why it happened?

**Comment by DavidMStraub** [comment]
Your appliance was offline, e.g. wi-fi switched off, when you tried to turn it off.

**Comment by DavidMStraub** [comment]
I assume this is not a bug, please re-open if you think otherwise.

**Comment by allmoney** [comment]
Turned OFF panel:
![20200506_165823](https://user-images.githubusercontent.com/939594/81186109-1dcf4280-8fbb-11ea-8096-3fda092a600a.jpg)

But status in HA not changed:
![image](https://user-images.githubusercontent.com/939594/81185891-d5178980-8fba-11ea-8ec8-1b2d14d7f009.png)

In Bosch app all is OK:
![Screenshot_20200506-165910_Home Connect](https://user-images.githubusercontent.com/939594/81186176-2d4e8b80-8fbb-11ea-8cab-c579d3c81709.jpg)

**Comment by DavidMStraub** [comment]
How is that related to your initial issue? This looks like #68 now.

**Comment by allmoney** [comment]
> How is that related to your initial issue? This looks like #68 now.
Sorry. Maybe. I don't know. Please, merge or transfer...
