### ISSUE TITLE
Translation directory changed...

### ISSUE THREAD

**Issue by pascalsaul** [DavidMStraub/homeassistant-homeconnect#77]
> 2020-05-05 22:37:34 WARNING (MainThread) [homeassistant.helpers.translation] homeconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

Little fix you should implement ;)

**Comment by DavidMStraub** [comment]
This is no translations directory. Which version are you on?

**Comment by DavidMStraub** [comment]
BTW, #72

**Comment by pascalsaul** [comment]
Home Assistant 0.109.4

-rw-r--r-- 1 root root  6474 Apr  5 21:19 switch.py
-rw-r--r-- 1 root root   414 Apr  5 21:19 strings.json
-rw-r--r-- 1 root root  2755 Apr  5 21:19 sensor.py
-rw-r--r-- 1 root root   274 Apr  5 21:19 manifest.json
-rw-r--r-- 1 root root  3118 Apr  5 21:19 __init__.py
-rw-r--r-- 1 root root   217 Apr  5 21:19 const.py
-rw-r--r-- 1 root root   882 Apr  5 21:19 config_flow.py
-rw-r--r-- 1 root root  2428 Apr  5 21:19 binary_sensor.py
-rw-r--r-- 1 root root 15645 Apr  5 21:19 api.py
drwxr-xr-x 4 root root  4096 Apr 15 18:23 ..
drwxr-xr-x 2 root root  4096 Apr 15 18:23 .translations

**Comment by DavidMStraub** [comment]
Right, that's outdated, so we can close this.
