### ISSUE TITLE
Old Entry in integrations cant be uninstalled and removed

### ISSUE THREAD

**Issue by mbrihed** [DavidMStraub/homeassistant-homeconnect#79]
Hi!
I removed the manual entry in configuration.yaml and uninstalled the "beta" add-on. But cant for the love of my life get rid of the integration in the main "Integration" View. It is still there and now I get a notification saying it cant be configured.

Something broke this.

**Comment by DavidMStraub** [comment]
It says "can't be configured" when you click the "delete" button in the integration view? Did you restart HA?

**Comment by mbrihed** [comment]
Hi!
I have restarted HA but not rebooted. And Yes, the notification says "can't be configured". And under Integrations the old entry is there but when you delete it it asks for confirmation but it never goes away. No error message or nothing. Will try a reboot of the Pi.

**Comment by mbrihed** [comment]
Tried a reboot and this is the message in the notification:

Invalid config
The following integrations and platforms could not be set up:
homeconnect
Please check your config.

I have no clue what to do...

**Comment by mbrihed** [comment]
OK, had to manually edit the file "core.config_entries" under config/.store and remove the entry. Now its gone and no more complains or notification from HA.

**Comment by anthonyangel** [comment]
I had the same, I think that I should have removed the integration before removing the custom component. - I edited the json files in .storage to remove any trace of the integration, the homeconnect devices or entities.

It might work to re-install the older version of the custom component through HACS, remove the integration and then upgrade.

**Comment by mbrihed** [comment]
Next question: Where do I find the official version? Do I have to wait for a new HA version? I am on 0.109.4

**Comment by anthonyangel** [comment]
It's in the dev branch at the moment, so you can swap to that if you want (although it's probably not a great idea)

Based on the release schedule there should be a beta of 0.110 released on 13th and a full release on 20th

**Comment by mbrihed** [comment]
Ah ok, thanks! I will just wait for the GA version of it. I am fine with out the integration for a couple of weeks.

**Comment by DavidMStraub** [comment]
I think this can be closed.
