### ISSUE TITLE
Logging in HASS

### ISSUE THREAD

**Issue by immert20** [DavidMStraub/homeassistant-homeconnect#8]
Can I edit the log level? Now I got very much log entries in HASS

**Comment by DavidMStraub** [comment]
You are right. I just changed the log level to "debug" everywhere where it is appropriate. You can now silence them by choosing

```yaml
logger:
  default: info
```

in your HA config.

**Comment by immert20** [comment]
I have that, but it looks like that you have no log level defined..

**Comment by DavidMStraub** [comment]
Not sure I understand what you mean. Did you use the new code including 72b8bbb?

**Comment by immert20** [comment]
Not yet
