### ISSUE TITLE
Programs Never Finish

### ISSUE THREAD

**Issue by jamiewalters** [DavidMStraub/homeassistant-homeconnect#83]
I noticed that:

Dryer Remaining Program Time never goes under 120s
Washing Machine Remaining Program never goes under 60s
Washing Machine Program Progress never goes over 95%

Is this a bug?

**Comment by DavidMStraub** [comment]
Which version of the integration are you using? I suspect not the current one (where the remaining program time is a timestamp sensor).

**Comment by jamiewalters** [comment]
Im running the version in the latest HA release.

**Comment by DavidMStraub** [comment]
I don't understand. The latest HA release does not contain this integration. Which version of this custom integration are you using? The one from the current master branch of this repository?

**Comment by jamiewalters** [comment]
I see now, I had both the old and new version running in HACS, the old wasn't removed for some reason.

**Comment by Zolli** [comment]
Hy, i also has this problem, i removed the old version (installed manually) and use the build-in version in the newest HA. The washing machine integration program_progress sensor could not get above 98, is this issue is still valid maybe?

**Comment by jamiewalters** [comment]
so it was for me, i think the version in HASS is the older version with the bug, I now run the version in HACS work fine.
