### ISSUE TITLE
unauthorized client with local IP adres

### ISSUE THREAD

**Issue by marcelwestrahome** [DavidMStraub/homeassistant-homeconnect#84]
I de- install the beta version (which was working) and try to install the HA version.

For on reason during set up I got with my local IP adres in the url.

http:
  base_url: !secret base_ur  # https://xxx.nl:443

home_connect:
  client_id: !secret home_connect_clientid
  client_secret: !secret home_connect_clientsecret

I had this problem before, did not remember how to solve :-(

{
  "error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized",
  "state": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmbG93X2lkIjoiOTliYWY2ODU1NWQ2NGE1YmFiYTkyYTBkNTQ4YjdmNGMifQ.ORpEuJkLzGs_w0Ar5ON5JHP_G77as9rd_-ZY6hUndes"
}

**Comment by DavidMStraub** [comment]
Might be related to the deprecation of `base_url` in 0.110, see the release notes. Try with `external_url`.

**Comment by ojalaj** [comment]
@DavidMStraub @marcelwestrahome I'm facing exactly the same issue. However, in my HA GUI the fields for setting external URL is greyed out, since I've manually configured configuration.yaml. Fine - but there is no documentation available for setting external_url in configuration.yaml. Do you know where to put it - under http?

**Comment by ojalaj** [comment]
Actually, by using base_url I got past this problem and got to the phase to add the integration, logging in with HC account and giving permission access the information and clicking OK, but then the browser gives me an error when trying to make a secure connection (SSL_ERROR_RX_RECORD_TOO_LONG). A dumb question - do I have to have enabled access to my HA (Pi3) from outside world using prot forwarding etc.?

**Comment by villevirtanen** [comment]
Same problem here.
I entered both internal _url and external_url under homeassistant: -section and I can see both values in HA GUI.
But when I now try to to add integration I see "client or redirection URI not authorized" error note. When I check url of the error page, it says that internal_url was used:

![image](https://user-images.githubusercontent.com/25028729/82490257-b3a2bb80-9aeb-11ea-8749-e802b7f9be46.png)

Tried to add integration using my HA internal URL and also using my HA URL via Nabu Casa.

**Comment by ojalaj** [comment]
@villevirtanen Should you have https instead of http in your url above?

**Comment by villevirtanen** [comment]
Tried also https but still same result.

**Comment by andre68723** [comment]
same as https://github.com/DavidMStraub/homeassistant-homeconnect/issues/52

**Comment by DagBertelsen** [comment]
I got the same problem, even tried to manually fix the redirectUrl in the link and open it manually. 
It will then seem to work and requires you log in on home-connect.com, but when it redirects back this stack trace is shown in the homeasssitant.log and home connect resets to open the link again:

```
TypeError: 'NoneType' object is not subscriptable
2020-05-22 07:58:23 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 125, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 91, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 248, in async_step_creation
    token = await self.flow_impl.async_resolve_external_data(self.external_data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 142, in async_resolve_external_data
    "redirect_uri": self.redirect_uri,
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 167, in _token_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url='https://api.home-connect.com/security/oauth/token
```

**Comment by zufivan** [comment]
I removed the following:
```
http:
  base_url: https://xxx.duckdns.org
```


I added: 
```
homeassisatnt:
  external_url: https://xxx.duckdns.org
  internal_url: https://xxx.duckdns.org
```
now the authorisation is working

**Comment by ojalaj** [comment]
@zufivan Good to hear - so do you mean that the integration is now working for you? One simple question which I already tried to ask above - do I need to expose my HA client to the Internet (port forwarding, dynamic dns etc.)?

**Comment by zufivan** [comment]
> @zufivan Good to hear - so do you mean that the integration is now working for you? One simple question which I already tried to ask above - do I need to expose my HA client to the Internet (port forwarding, dynamic dns etc.)?

yes, you need to configure port forwarding and dynamic dns)

**Comment by ojalaj** [comment]
@zufivan OK thanks. I think this information was lacking and actually in readme it says that "(it will not work without https, but your Home Assistant instance does not have to be accessible from the internet and a self-signed certificate will do)"....hmmm?

**Comment by ebnerjoh** [comment]
Should it work via nabu.casa as well?

**Comment by marcelwestrahome** [comment]
Yes , adding this to my configuration (without the typepo works for me also)

homeassistant:
  external_url: !secret base_url
  internal_url: !secret base_url



Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: zufivan<mailto:notifications@github.com>
Verzonden: vrijdag 22 mei 2020 09:00
Aan: DavidMStraub/homeassistant-homeconnect<mailto:homeassistant-homeconnect@noreply.github.com>
CC: marcelwestrahome<mailto:marcel_westra@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Onderwerp: Re: [DavidMStraub/homeassistant-homeconnect] unauthorized client with local IP adres (#84)


@zufivan<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzufivan&data=02%7C01%7C%7C6b4dec8db1304c9ebaa408d7fe1dd8b3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637257276443240058&sdata=wEA%2B8Jq3vafJfxvr02Z1GrzLZ18eTZxzeiNkpeG%2Ffe0%3D&reserved=0> Good to hear - so do you mean that the integration is now working for you? One simple question which I already tried to ask above - do I need to expose my HA client to the Internet (port forwarding, dynamic dns etc.)?

yes, you need to configure port forwarding and dynamic dns)

**Comment by marcelwestrahome** [comment]
issued solved see last post

**Comment by ojalaj** [comment]
@marcelwestrahome Great that you got it working! Two final questions/confirmations:
1) Are your external_url and internal_url identical?
2) Is your !secret base_url some address with which your HA client can be accessed from the Internet?

At least for me putting external_url=internal_url = https://192.168.X.XXX:8123 does not work. So ultimately I just want to confirm that do I really need to make my HA accessible from the Internet, as already confirmed by @zufivan above, but not supported by the documentation. @villevirtanen @DagBertelsen ?

**Comment by DagBertelsen** [comment]
That seems to have fixed it. setting internal and external to the same.

I have exposed my to the outside world, but I'm not sure if you can expose it for a short time and deactivate it again.

**Comment by DavidMStraub** [comment]
You definitely do not need to expose your instance to the outside world. When authorizing through the browser, you will be forwarded to the redirect URI and this way your Home Assistant instance will get all the required data. So you *have* to be able to access Home Assistant through `https://192.168.X.XXX:8123 `. That's all that matters.

**Comment by DavidMStraub** [comment]
See also https://github.com/home-assistant/core/issues/35844.

**Comment by ojalaj** [comment]
@DavidMStraub Thank you for this piece of work and help with the issue. Now the issue seems to be solved for me. The trick was that I had **https** in my "https://192.168.X.XXX:8123" for external_url & internal_url and Redirect URL in Home Connect API - now when I changed it to **http** external_url & internal_url - boom, it works. Somewhere during the path I also got lost to trying to expose my HA to the world through DuckDNS etc (see above). 

https://github.com/DavidMStraub/homeassistant-homeconnect/issues/52
https://github.com/home-assistant/core/issues/35844

**Comment by marcelwestrahome** [comment]
Yes, they are identical
Yes, it can be accessed from the internet

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
