### ISSUE TITLE
The given user is not assigned to this application

### ISSUE THREAD

**Issue by Christianb233** [DavidMStraub/homeassistant-homeconnect#90]
Hello, after reading all the issues and double-checking that my process follows the instruction, I propose to you this issue because I don't find solution :-(
I have :
- Registered an account with the Home Connect Developer Program
- Registered a new application with OAuth Flow type Authorization Code Grant Flow and Redirect URI http://192.168.xx.xx:8123/auth/external/callback 
- Added the following text to your configuration.yaml:
home_connect:
  client_id: MY_CLIENT_ID
  client_secret: MY_CLIENT_SECRET
- Installed Home connect via HACS 
- Navigated to the Integrations page and select "Home Connect"
- A new webpage opens : https://api.home-connect.com/security/oauth/login asking me to connect to my Home Connect account for linking the application to my product; but after writing the login/password of my smartphone Home Connect app, it returns : "The given user is not assigned to this application" :-(
I thank you in advance for your help !

**Other information**
On configuration.yaml, I understood that we needed to type "home_connect" and no "home_connect_beta" anymore.
In the "custom_components" directory, there is a "home_connect_beta" directory
Home assistant installed on a docker of a Raspberry PI 3B+ with Raspbian buster desktop

**For Home Connect app**
A Bosch dischwasher device is working on that app

Do I need to define something particular into this app ?

**For Home Assistant:**
Home Assistant 0.110.2
Source: serveur — interface utilisateur
Version interface utilisateur : 20200519.4 - latest

arch | armv7l
dev | false
docker | true
hassio | true
host_os | Raspbian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.19.97-v7+
python_version | 3.7.7
supervisor | 224
timezone | Europe/Paris
version | 0.110.2
virtualenv | false

**Comment by DavidMStraub** [comment]
Use your Home Connect developer account credentials.

**Comment by Christianb233** [comment]
I have the same email and password on Home Connect developer account.
Do I need to put a different email and password (so to create another login and password on Home Connect developer account > new application > copy-paste CLIENT_ID, CLIENT_SECRET...) ?

**Comment by DavidMStraub** [comment]
I don't know why it doesn't work, but it's definitely not an issue with Home Assistant or this integration. It's says the user is not assigned to the application, so please double-check your Home Connect app settings.

Since I'm currently overwhelmed by new issues with authentication problems that are external to this integration, please understand that I will close this issue. I advise you to start a thread in the community forum instead.
