### ISSUE TITLE
Door sensor does not update on washing machine and dryer

### ISSUE THREAD

**Issue by Veuchez** [DavidMStraub/homeassistant-homeconnect#91]
Hi, I have two devices (Bosch WTY877H8IT Dryer and Bosch WAW286H8IT Washing Machine) that do not update the status of the open / closed door.
When a program is running, however, I see that the door is open.
Or if the door is open, I see it closed.
If it tries to open and close continuously the status does not update.
On other devices such as oven and dishwasher, the status is updated immediately.
Thanks.

**Comment by Veuchez** [comment]
Now works.  
Before I had also restarted home assistant several times without result .. very strange.

**Comment by DavidMStraub** [comment]
It might have been an API glitch.
