### ISSUE TITLE
Pause programs

### ISSUE THREAD

**Issue by Veuchez** [DavidMStraub/homeassistant-homeconnect#92]
Is it possible to pause an active program for example on the washing machine, dryer and dishwasher?
Should I always have remote control active on the device?

**Comment by DavidMStraub** [comment]
This is not implemented. Modeling a program as a switch, this cannot be done, but it could be by adding service calls (#23, #49).

**Comment by DavidMStraub** [comment]
Closing in favour of #23, will add a comment there.
